name: ARTIFACT
  on:[on push]
 env: 
 ARTIFACT_NAME: artifact
 jobs:
 build:
      name: Build
      runs-on: ubuntu-latest
      steps:
    - name : Check out code
      uses: actions/checkout@v2
    - name: upload the artifact
      use: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
